shallow_clone: true

os: Visual Studio 2015
platform:
  - x86
  - x64

build_script:
  - c:\cygwin\bin\sh -lc "env"
  - c:\cygwin\bin\sh -lc "ls -l $OLDPWD"
  - c:\cygwin\bin\sh -lc "(cd $OLDPWD; pwd; ls -l)"
  

