shallow_clone: true

os: Visual Studio 2015
platform:
  - x86
  - x64

build_script:
  - c:\cygwin\bin\sh -lc "(cd $OLDPWD; ./autogen.sh;)"
  - c:\cygwin\bin\sh -lc "(cd $OLDPWD; ./configure CC='`pwd`/msvcc.sh -clang-cl' CXX='`pwd`/msvcc.sh -clang-cl' LD=link CPP='clang-cl -EP'; cat `find ./ -name config.log`)"
  

  
  

